from django.db import models
from django_pandas.managers import DataFrameManager
# Create your models here.
import json

class Dataset(models.Model):
	age = models.IntegerField(null=True, blank=True)
	sex = models.FloatField(null=True, blank=True)
	steroid = models.FloatField(null=True, blank=True)
	antivirals = models.FloatField(null=True, blank=True)
	fatigue = models.FloatField(null=True, blank=True)
	malaise = models.FloatField(null=True, blank=True)
	anorexia = models.FloatField(null=True, blank=True)
	liver_big = models.FloatField(null=True, blank=True)
	liver_firm = models.FloatField(null=True, blank=True)
	spleen_palpable = models.FloatField(null=True, blank=True)
	spiders = models.FloatField(null=True, blank=True)
	ascites = models.FloatField(null=True, blank=True)
	varices = models.FloatField(null=True, blank=True)
	bilirubin = models.FloatField(null=True, blank=True)
	alk_posphate = models.FloatField(null=True, blank=True)
	sgot = models.FloatField(null=True, blank=True)
	albumin = models.FloatField(null=True, blank=True)
	protime = models.FloatField(null=True, blank=True)
	histology = models.FloatField(null=True, blank=True)
	kelas = models.IntegerField(null=True, blank=True)


class DatasetPreprocessing(models.Model):
	age = models.FloatField(null=True, blank=True)
	sex = models.FloatField(null=True, blank=True)
	steroid = models.FloatField(null=True, blank=True)
	antivirals = models.FloatField(null=True, blank=True)
	fatigue = models.FloatField(null=True, blank=True)
	malaise = models.FloatField(null=True, blank=True)
	anorexia = models.FloatField(null=True, blank=True)
	liver_big = models.FloatField(null=True, blank=True)
	liver_firm = models.FloatField(null=True, blank=True)
	spleen_palpable = models.FloatField(null=True, blank=True)
	spiders = models.FloatField(null=True, blank=True)
	ascites = models.FloatField(null=True, blank=True)
	varices = models.FloatField(null=True, blank=True)
	bilirubin = models.FloatField(null=True, blank=True)
	alk_posphate = models.FloatField(null=True, blank=True)
	sgot = models.FloatField(null=True, blank=True)
	albumin = models.FloatField(null=True, blank=True)
	protime = models.FloatField(null=True, blank=True)
	histology = models.FloatField(null=True, blank=True)
	kelas = models.FloatField(null=True, blank=True)


class Inisialisasi(models.Model):
	epochs = models.IntegerField(null=True, blank=True)
	persen_uji = models.FloatField(null=True, blank=True)
	lr = models.FloatField(null=True, blank=True)
	pengurangan_lr = models.FloatField(null=True, blank=True)
	minimum_lr = models.FloatField(null=True, blank=True)
	window = models.FloatField(null=True, blank=True)


class BobotAwal(models.Model):
	dataset_id = models.IntegerField(null=True, blank=True)
	x1 = models.FloatField(null=True, blank=True)
	x2 = models.FloatField(null=True, blank=True)
	x3 = models.FloatField(null=True, blank=True)
	x4 = models.FloatField(null=True, blank=True)
	x5 = models.FloatField(null=True, blank=True)
	x6 = models.FloatField(null=True, blank=True)
	x7 = models.FloatField(null=True, blank=True)
	x8 = models.FloatField(null=True, blank=True)
	x9 = models.FloatField(null=True, blank=True)
	x10 = models.FloatField(null=True, blank=True)
	x11 = models.FloatField(null=True, blank=True)
	x12 = models.FloatField(null=True, blank=True)
	x13 = models.FloatField(null=True, blank=True)
	x14 = models.FloatField(null=True, blank=True)
	x15 = models.FloatField(null=True, blank=True)
	x16 = models.FloatField(null=True, blank=True)
	x17 = models.FloatField(null=True, blank=True)
	x18 = models.FloatField(null=True, blank=True)
	x19 = models.FloatField(null=True, blank=True) 
	kelas = models.IntegerField(null=True, blank=True) 

class BobotAkhir(models.Model):
	x1 = models.FloatField(null=True, blank=True)
	x2 = models.FloatField(null=True, blank=True)
	x3 = models.FloatField(null=True, blank=True)
	x4 = models.FloatField(null=True, blank=True)
	x5 = models.FloatField(null=True, blank=True)
	x6 = models.FloatField(null=True, blank=True)
	x7 = models.FloatField(null=True, blank=True)
	x8 = models.FloatField(null=True, blank=True)
	x9 = models.FloatField(null=True, blank=True)
	x10 = models.FloatField(null=True, blank=True)
	x11 = models.FloatField(null=True, blank=True)
	x12 = models.FloatField(null=True, blank=True)
	x13 = models.FloatField(null=True, blank=True)
	x14 = models.FloatField(null=True, blank=True)
	x15 = models.FloatField(null=True, blank=True)
	x16 = models.FloatField(null=True, blank=True)
	x17 = models.FloatField(null=True, blank=True)
	x18 = models.FloatField(null=True, blank=True)
	x19 = models.FloatField(null=True, blank=True) 
	kelas = models.IntegerField(null=True, blank=True)
	metode = models.CharField(max_length=20)