from django.urls import path

from . import views

urlpatterns = [
    path('inisialisasi_data_awal', views.inisialisasi_data_awal, name='lvq/inisialisasi_data_awal'),
    path('tambah_data_awal', views.tambah_data_awal, name='lvq/tambah_data_awal'),
    path('simpan_inisialisasi', views.simpan_inisialisasi, name='lvq/simpan_inisialisasi'),
    path('json_data_awal', views.json_data_awal, name='lvq/json_data_awal'),
    path('proses_tambah_data_awal', views.proses_tambah_data_awal, name='lvq/proses_tambah_data_awal'),
    path('proses_import_data_awal', views.proses_import_data_awal, name='lvq/proses_import_data_awal'),
    path('edit_data_awal/<id_data>', views.edit_data_awal, name='lvq/edit_data_awal'),
    path('proses_edit_data_awal', views.proses_edit_data_awal, name='lvq/proses_edit_data_awal'),
    path('proses_hapus_data_awal', views.proses_hapus_data_awal, name='lvq/proses_hapus_data_awal'),
    path('proses_hapus_satu_data_awal', views.proses_hapus_satu_data_awal, name='lvq/proses_hapus_satu_data_awal'),
    path('preprocessing', views.preprocessing, name='lvq/preprocessing'),
    path('proses_preprocessing', views.proses_preprocessing, name='lvq/proses_preprocessing'),
    path('proses_hapus_data_preprocessing', views.proses_hapus_data_preprocessing, name='lvq/proses_hapus_data_preprocessing'),
    path('json_data_preprocessing', views.json_data_preprocessing, name='lvq/json_data_preprocessing'),
    path('training_data', views.training_data, name='lvq/training_data'),
    path('generate_bobot_awal', views.generate_bobot_awal, name='lvq/generate_bobot_awal'),
    path('json_bobot_awal', views.json_bobot_awal, name='lvq/json_bobot_awal'),
    path('json_data_latih_uji', views.json_data_latih_uji, name='lvq/json_data_latih_uji'),
    path('perbandingan_lvq', views.perbandingan_lvq, name='lvq/perbandingan_lvq'),
    path('proses_perbandingan_lvq', views.proses_perbandingan_lvq, name='lvq/proses_perbandingan_lvq'),
    path('pelatihan_lvq', views.pelatihan_lvq, name='lvq/pelatihan_lvq'),
    path('pelatihan_lvq2', views.pelatihan_lvq2, name='lvq/pelatihan_lvq2'),
    path('pelatihan_lvq21', views.pelatihan_lvq21, name='lvq/pelatihan_lvq21'),
    path('generate_data_uji', views.generate_data_uji, name='lvq/generate_data_uji'),
    path('generate_bobot_akhir', views.generate_bobot_akhir, name='lvq/generate_bobot_akhir'),
    path('testing_data', views.testing_data, name='lvq/testing_data'),
    path('testing_data_lvq2', views.testing_data_lvq2, name='lvq/testing_data_lvq2'),
    path('testing_data_lvq21', views.testing_data_lvq21, name='lvq/testing_data_lvq21'),
    path('proses_testing_lvq', views.proses_testing_lvq, name='lvq/proses_testing_lvq'),
]
