# Generated by Django 3.1.4 on 2021-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0002_datasetpreprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inisialisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('persen_uji', models.FloatField(blank=True, null=True)),
                ('learning_rate', models.FloatField(blank=True, null=True)),
                ('pengurangan_learning_rate', models.FloatField(blank=True, null=True)),
                ('minimum_learning_rate', models.FloatField(blank=True, null=True)),
                ('window', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
