# Generated by Django 3.1.4 on 2021-01-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0003_inisialisasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKlasifikasiLVQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(blank=True, null=True)),
                ('kelas', models.IntegerField(blank=True, null=True)),
                ('kelas_predicted', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HasilKlasifikasiLVQ21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(blank=True, null=True)),
                ('kelas', models.IntegerField(blank=True, null=True)),
                ('kelas_predicted', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
