# Generated by Django 3.1.4 on 2021-01-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0004_hasilklasifikasilvq2_hasilklasifikasilvq21'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HasilKlasifikasiLVQ2',
        ),
        migrations.DeleteModel(
            name='HasilKlasifikasiLVQ21',
        ),
        migrations.RenameField(
            model_name='inisialisasi',
            old_name='learning_rate',
            new_name='lr',
        ),
        migrations.RenameField(
            model_name='inisialisasi',
            old_name='minimum_learning_rate',
            new_name='minimum_lr',
        ),
        migrations.RenameField(
            model_name='inisialisasi',
            old_name='pengurangan_learning_rate',
            new_name='pengurangan_lr',
        ),
    ]
