# Generated by Django 3.1.4 on 2021-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvq', '0005_auto_20210118_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotAkhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('x3', models.FloatField(blank=True, null=True)),
                ('x4', models.FloatField(blank=True, null=True)),
                ('x5', models.FloatField(blank=True, null=True)),
                ('x6', models.FloatField(blank=True, null=True)),
                ('x7', models.FloatField(blank=True, null=True)),
                ('x8', models.FloatField(blank=True, null=True)),
                ('x9', models.FloatField(blank=True, null=True)),
                ('x10', models.FloatField(blank=True, null=True)),
                ('x11', models.FloatField(blank=True, null=True)),
                ('x12', models.FloatField(blank=True, null=True)),
                ('x13', models.FloatField(blank=True, null=True)),
                ('x14', models.FloatField(blank=True, null=True)),
                ('x15', models.FloatField(blank=True, null=True)),
                ('x16', models.FloatField(blank=True, null=True)),
                ('x17', models.FloatField(blank=True, null=True)),
                ('x18', models.FloatField(blank=True, null=True)),
                ('x19', models.FloatField(blank=True, null=True)),
                ('kelas', models.IntegerField(blank=True, null=True)),
                ('metode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BobotAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('x3', models.FloatField(blank=True, null=True)),
                ('x4', models.FloatField(blank=True, null=True)),
                ('x5', models.FloatField(blank=True, null=True)),
                ('x6', models.FloatField(blank=True, null=True)),
                ('x7', models.FloatField(blank=True, null=True)),
                ('x8', models.FloatField(blank=True, null=True)),
                ('x9', models.FloatField(blank=True, null=True)),
                ('x10', models.FloatField(blank=True, null=True)),
                ('x11', models.FloatField(blank=True, null=True)),
                ('x12', models.FloatField(blank=True, null=True)),
                ('x13', models.FloatField(blank=True, null=True)),
                ('x14', models.FloatField(blank=True, null=True)),
                ('x15', models.FloatField(blank=True, null=True)),
                ('x16', models.FloatField(blank=True, null=True)),
                ('x17', models.FloatField(blank=True, null=True)),
                ('x18', models.FloatField(blank=True, null=True)),
                ('x19', models.FloatField(blank=True, null=True)),
                ('kelas', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
